// Code generated by mxgen. DO NOT EDIT.
package mx

func (n *Node) DocType()                                      { Raw(`<!DOCTYPE html>`)(n) }
func (n *Node) A(attr Attr, children ...func(*Node))          { n.el("a", attr, children...) }
func (n *Node) Abbr(attr Attr, children ...func(*Node))       { n.el("abbr", attr, children...) }
func (n *Node) Address(attr Attr, children ...func(*Node))    { n.el("address", attr, children...) }
func (n *Node) Area(attr Attr)                                { n.el("area", attr) }
func (n *Node) Article(attr Attr, children ...func(*Node))    { n.el("article", attr, children...) }
func (n *Node) Aside(attr Attr, children ...func(*Node))      { n.el("aside", attr, children...) }
func (n *Node) Audio(attr Attr, children ...func(*Node))      { n.el("audio", attr, children...) }
func (n *Node) B(attr Attr, children ...func(*Node))          { n.el("b", attr, children...) }
func (n *Node) Base(attr Attr)                                { n.el("base", attr) }
func (n *Node) Bdi(attr Attr, children ...func(*Node))        { n.el("bdi", attr, children...) }
func (n *Node) Bdo(attr Attr, children ...func(*Node))        { n.el("bdo", attr, children...) }
func (n *Node) Blockquote(attr Attr, children ...func(*Node)) { n.el("blockquote", attr, children...) }
func (n *Node) Body(attr Attr, children ...func(*Node))       { n.el("body", attr, children...) }
func (n *Node) Br(attr Attr)                                  { n.el("br", attr) }
func (n *Node) Button(attr Attr, children ...func(*Node))     { n.el("button", attr, children...) }
func (n *Node) Canvas(attr Attr, children ...func(*Node))     { n.el("canvas", attr, children...) }
func (n *Node) Caption(attr Attr, children ...func(*Node))    { n.el("caption", attr, children...) }
func (n *Node) Cite(attr Attr, children ...func(*Node))       { n.el("cite", attr, children...) }
func (n *Node) Code(attr Attr, children ...func(*Node))       { n.el("code", attr, children...) }
func (n *Node) Col(attr Attr)                                 { n.el("col", attr) }
func (n *Node) Colgroup(attr Attr, children ...func(*Node))   { n.el("colgroup", attr, children...) }
func (n *Node) Data(attr Attr, children ...func(*Node))       { n.el("data", attr, children...) }
func (n *Node) Datalist(attr Attr, children ...func(*Node))   { n.el("datalist", attr, children...) }
func (n *Node) Dd(attr Attr, children ...func(*Node))         { n.el("dd", attr, children...) }
func (n *Node) Del(attr Attr, children ...func(*Node))        { n.el("del", attr, children...) }
func (n *Node) Details(attr Attr, children ...func(*Node))    { n.el("details", attr, children...) }
func (n *Node) Dfn(attr Attr, children ...func(*Node))        { n.el("dfn", attr, children...) }
func (n *Node) Dialog(attr Attr, children ...func(*Node))     { n.el("dialog", attr, children...) }
func (n *Node) Div(attr Attr, children ...func(*Node))        { n.el("div", attr, children...) }
func (n *Node) Dl(attr Attr, children ...func(*Node))         { n.el("dl", attr, children...) }
func (n *Node) Dt(attr Attr, children ...func(*Node))         { n.el("dt", attr, children...) }
func (n *Node) Em(attr Attr, children ...func(*Node))         { n.el("em", attr, children...) }
func (n *Node) Embed(attr Attr)                               { n.el("embed", attr) }
func (n *Node) Fieldset(attr Attr, children ...func(*Node))   { n.el("fieldset", attr, children...) }
func (n *Node) Figcaption(attr Attr, children ...func(*Node)) { n.el("figcaption", attr, children...) }
func (n *Node) Figure(attr Attr, children ...func(*Node))     { n.el("figure", attr, children...) }
func (n *Node) Footer(attr Attr, children ...func(*Node))     { n.el("footer", attr, children...) }
func (n *Node) Form(attr Attr, children ...func(*Node))       { n.el("form", attr, children...) }
func (n *Node) H1(attr Attr, children ...func(*Node))         { n.el("h1", attr, children...) }
func (n *Node) H2(attr Attr, children ...func(*Node))         { n.el("h2", attr, children...) }
func (n *Node) H3(attr Attr, children ...func(*Node))         { n.el("h3", attr, children...) }
func (n *Node) H4(attr Attr, children ...func(*Node))         { n.el("h4", attr, children...) }
func (n *Node) H5(attr Attr, children ...func(*Node))         { n.el("h5", attr, children...) }
func (n *Node) H6(attr Attr, children ...func(*Node))         { n.el("h6", attr, children...) }
func (n *Node) Head(attr Attr, children ...func(*Node))       { n.el("head", attr, children...) }
func (n *Node) Header(attr Attr, children ...func(*Node))     { n.el("header", attr, children...) }
func (n *Node) Hr(attr Attr)                                  { n.el("hr", attr) }
func (n *Node) Html(attr Attr, children ...func(*Node))       { n.el("html", attr, children...) }
func (n *Node) I(attr Attr, children ...func(*Node))          { n.el("i", attr, children...) }
func (n *Node) Iframe(attr Attr, children ...func(*Node))     { n.el("iframe", attr, children...) }
func (n *Node) Img(attr Attr)                                 { n.el("img", attr) }
func (n *Node) Input(attr Attr)                               { n.el("input", attr) }
func (n *Node) Ins(attr Attr, children ...func(*Node))        { n.el("ins", attr, children...) }
func (n *Node) Kbd(attr Attr, children ...func(*Node))        { n.el("kbd", attr, children...) }
func (n *Node) Label(attr Attr, children ...func(*Node))      { n.el("label", attr, children...) }
func (n *Node) Legend(attr Attr, children ...func(*Node))     { n.el("legend", attr, children...) }
func (n *Node) Li(attr Attr, children ...func(*Node))         { n.el("li", attr, children...) }
func (n *Node) Link(attr Attr)                                { n.el("link", attr) }
func (n *Node) Main(attr Attr, children ...func(*Node))       { n.el("main", attr, children...) }
func (n *Node) Map(attr Attr, children ...func(*Node))        { n.el("map", attr, children...) }
func (n *Node) Mark(attr Attr, children ...func(*Node))       { n.el("mark", attr, children...) }
func (n *Node) Meta(attr Attr)                                { n.el("meta", attr) }
func (n *Node) Meter(attr Attr, children ...func(*Node))      { n.el("meter", attr, children...) }
func (n *Node) Nav(attr Attr, children ...func(*Node))        { n.el("nav", attr, children...) }
func (n *Node) Noscript(attr Attr, children ...func(*Node))   { n.el("noscript", attr, children...) }
func (n *Node) Object(attr Attr, children ...func(*Node))     { n.el("object", attr, children...) }
func (n *Node) Ol(attr Attr, children ...func(*Node))         { n.el("ol", attr, children...) }
func (n *Node) Optgroup(attr Attr, children ...func(*Node))   { n.el("optgroup", attr, children...) }
func (n *Node) Option(attr Attr, children ...func(*Node))     { n.el("option", attr, children...) }
func (n *Node) Output(attr Attr, children ...func(*Node))     { n.el("output", attr, children...) }
func (n *Node) P(attr Attr, children ...func(*Node))          { n.el("p", attr, children...) }
func (n *Node) Picture(attr Attr, children ...func(*Node))    { n.el("picture", attr, children...) }
func (n *Node) Pre(attr Attr, children ...func(*Node))        { n.el("pre", attr, children...) }
func (n *Node) Progress(attr Attr, children ...func(*Node))   { n.el("progress", attr, children...) }
func (n *Node) Q(attr Attr, children ...func(*Node))          { n.el("q", attr, children...) }
func (n *Node) Rp(attr Attr, children ...func(*Node))         { n.el("rp", attr, children...) }
func (n *Node) Rt(attr Attr, children ...func(*Node))         { n.el("rt", attr, children...) }
func (n *Node) Ruby(attr Attr, children ...func(*Node))       { n.el("ruby", attr, children...) }
func (n *Node) S(attr Attr, children ...func(*Node))          { n.el("s", attr, children...) }
func (n *Node) Samp(attr Attr, children ...func(*Node))       { n.el("samp", attr, children...) }
func (n *Node) Script(attr Attr, children ...func(*Node))     { n.el("script", attr, children...) }
func (n *Node) Section(attr Attr, children ...func(*Node))    { n.el("section", attr, children...) }
func (n *Node) Select(attr Attr, children ...func(*Node))     { n.el("select", attr, children...) }
func (n *Node) Slot(attr Attr, children ...func(*Node))       { n.el("slot", attr, children...) }
func (n *Node) Small(attr Attr, children ...func(*Node))      { n.el("small", attr, children...) }
func (n *Node) Source(attr Attr)                              { n.el("source", attr) }
func (n *Node) Span(attr Attr, children ...func(*Node))       { n.el("span", attr, children...) }
func (n *Node) Strong(attr Attr, children ...func(*Node))     { n.el("strong", attr, children...) }
func (n *Node) Style(attr Attr, children ...func(*Node))      { n.el("style", attr, children...) }
func (n *Node) Sub(attr Attr, children ...func(*Node))        { n.el("sub", attr, children...) }
func (n *Node) Summary(attr Attr, children ...func(*Node))    { n.el("summary", attr, children...) }
func (n *Node) Sup(attr Attr, children ...func(*Node))        { n.el("sup", attr, children...) }
func (n *Node) SVG(attr Attr, children ...func(*Node))        { n.el("svg", attr, children...) }
func (n *Node) Table(attr Attr, children ...func(*Node))      { n.el("table", attr, children...) }
func (n *Node) Tbody(attr Attr, children ...func(*Node))      { n.el("tbody", attr, children...) }
func (n *Node) Td(attr Attr, children ...func(*Node))         { n.el("td", attr, children...) }
func (n *Node) Template(attr Attr, children ...func(*Node))   { n.el("template", attr, children...) }
func (n *Node) Textarea(attr Attr, children ...func(*Node))   { n.el("textarea", attr, children...) }
func (n *Node) Tfoot(attr Attr, children ...func(*Node))      { n.el("tfoot", attr, children...) }
func (n *Node) Th(attr Attr, children ...func(*Node))         { n.el("th", attr, children...) }
func (n *Node) Thead(attr Attr, children ...func(*Node))      { n.el("thead", attr, children...) }
func (n *Node) Time(attr Attr, children ...func(*Node))       { n.el("time", attr, children...) }
func (n *Node) Title(attr Attr, children ...func(*Node))      { n.el("title", attr, children...) }
func (n *Node) Tr(attr Attr, children ...func(*Node))         { n.el("tr", attr, children...) }
func (n *Node) Track(attr Attr)                               { n.el("track", attr) }
func (n *Node) U(attr Attr, children ...func(*Node))          { n.el("u", attr, children...) }
func (n *Node) Ul(attr Attr, children ...func(*Node))         { n.el("ul", attr, children...) }
func (n *Node) Var(attr Attr, children ...func(*Node))        { n.el("var", attr, children...) }
func (n *Node) Video(attr Attr, children ...func(*Node))      { n.el("video", attr, children...) }
func (n *Node) Wbr(attr Attr)                                 { n.el("wbr", attr) }
